CREATE TABLE `fund` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `com_id` bigint(20) NOT NULL COMMENT '所属公司',
  `name` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '基金名称',
  `code` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '基金编码',
  `short_name` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '基金简称',
  `status` int(11) NOT NULL DEFAULT 0 COMMENT '基金状态 0-未知 1-投资中 2-投资结束 3-退出 4-延长期 5-清算阶段 6-清算完毕 7-其他',
  `org_type` int(11) NOT NULL DEFAULT 0 COMMENT '基金组织类型 0-未知 1-契约型 2-公司型 3-合伙型 4-其他',
  `management_mode` int(11) NOT NULL DEFAULT 0 COMMENT '管理模式 0-未知 1-主导型 2-混合型 3-参与型',
  `social_credit_code` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '社会信用号',
  `province_id` bigint(20) DEFAULT NULL COMMENT '省ID',
  `city_id` bigint(20) DEFAULT NULL COMMENT '市ID',
  `addr` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '详细地址',
  `exec_partner_type` int(11) NOT NULL DEFAULT 0 COMMENT '执行事务合伙人类型 0-未知 1-基金管理人 2-内部机构 3-外部机构',
  `exec_partner_id` bigint(20) DEFAULT NULL COMMENT '执行事务合伙人ID',
  `delegate_id` bigint(20) DEFAULT NULL COMMENT '委派代表(联系人)ID',
  `establish_date` datetime DEFAULT NULL COMMENT '成立日期',
  `duration` int(11) DEFAULT NULL COMMENT '基金存续期(年)',
  `invest_period` int(11) DEFAULT NULL COMMENT '投资期(年)',
  `expir_date` datetime DEFAULT NULL COMMENT '到期日期',
  `invest_start_date` datetime DEFAULT NULL COMMENT '投资开始日期',
  `invest_end_date` datetime DEFAULT NULL COMMENT '投资结束日期',
  `liquidate_date` datetime DEFAULT NULL COMMENT '清算日期',
  `extend_period` int(11) DEFAULT NULL COMMENT '延长期(年)',
  `extend_start_date` datetime DEFAULT NULL COMMENT '延长起始日期',
  `extend_end_date` datetime DEFAULT NULL COMMENT '延长结束日期',
  `floor_earnings_rate` decimal(18,8) DEFAULT NULL COMMENT '基金门槛收益率（%）',
  `expect_raise_amount` decimal(18,8) DEFAULT NULL COMMENT '基金目标募集规模（万元）',
  `actual_raise_amount` decimal(18,8) DEFAULT NULL COMMENT '基金实际募资规模（万元）',
  `currency_id` bigint(20) DEFAULT NULL COMMENT '货币ID',
  `vote_type` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '投决机制',
  `invest_direction` varchar(255) CHARACTER SET utf8 DEFAULT NULL COMMENT '投资方向',
  `share_type` int(11) NOT NULL DEFAULT 0 COMMENT '份额类型 0-未知 1-无特殊 2-分级基金 3-伞型基金 4-结构化基金 5-其他',
  `leverage` decimal(18,8) DEFAULT NULL COMMENT '杠杆比例(%)',
  `management_type` int(11) NOT NULL DEFAULT 0 COMMENT '管理类型 0-未知 1-受托管理 2-顾问管理 3-自我管理 4-参与管理',
  `vote_radio` decimal(18,8) DEFAULT NULL COMMENT '我方占基金投决委员会比例（%）',
  `is_audited` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否完成审核',
  `is_fixed_fee` tinyint(4) NOT NULL DEFAULT 0 COMMENT '管理费是否固定比例',
  `is_entrusted` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否托管',
  `is_fof` tinyint(4) NOT NULL DEFAULT 0 COMMENT '是否为母基金',
  `entrusted_id` bigint(20) DEFAULT NULL COMMENT '基金托管人ID',
  `created_by` bigint(20) DEFAULT NULL,
  `updated_by` bigint(20) DEFAULT NULL,
  `removed_by` bigint(20) DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `removed_at` datetime DEFAULT NULL,
  `version` int(11) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;